# Generated by Django 4.2.13 on 2026-06-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ai_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='ai_analysis_status',
            field=models.CharField(choices=[('not_required', 'AI解析不要'), ('pending', 'AI解析待ち'), ('processing', 'AI解析中'), ('completed', 'AI解析完了'), ('error', 'AI解析エラー')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='ai_error_message',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='image',
            name='ai_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='ai_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='ai_response_text',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['ai_analysis_status', '-captured_at'], name='core_image_ai_anal_3d861b_idx'),
        ),
    ]
